config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "books#index"
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: "users/registrations"

  }
  resources :users, only: [:index, :show]
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  mount_uploader :picture, PictureUploader
  DEFAULT_PAGINATES_PER = 20
  paginates_per DEFAULT_PAGINATES_PER
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.page(params[:page])
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: t("notice.new") }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: t("notice.update") }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: t("notice.destroy") }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :memo, :author, :picture)
    end
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :memo %>
    <%= form.text_area :memo %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1><%= t('button.edit') %></h1>

<%= render 'form', book: @book %>

<%= link_to  t('button.show'), @book %> |
<%= link_to  t('button.back'), books_path %>

app/views/books/index.html.erb
<h1><%= Book.model_name.human %></h1>

<table>
  <thead>
    <tr>
      <th><%= Book.human_attribute_name(:title) %></th>
      <th><%= Book.human_attribute_name(:memo) %></th>
      <th><%= Book.human_attribute_name(:author) %></th>
      <th><%= Book.human_attribute_name(:picture) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.memo %></td>
        <td><%= book.author %></td>
        <td><%= book.picture %></td>
        <td><%= link_to t('button.show'), book %></td>
        <td><%= link_to t('button.edit'), edit_book_path(book) %></td>
        <td><%= link_to t('button.destroy'), book, method: :delete, data: { confirm: t('notice.confirm_message') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<hr>
<%= page_entries_info @books %>
<%= paginate @books %><br><br>
<%= link_to  t('button.new_book'), new_book_path %><br>
<%= link_to t('button.user_index'), users_path %>

app/views/books/new.html.erb
<h1><%= t('button.new_book') %></h1>

<%= render 'form', book: @book %>

<%= link_to  t('button.back'), books_path %>

app/views/books/show.html.erb
<p>
  <strong><%= Book.human_attribute_name(:title) %>:</strong>
  <%= @book.title %>
</p>

<p>
  <strong><%= Book.human_attribute_name(:memo) %>:</strong>
  <%= @book.memo %>
</p>

<p>
  <strong><%= Book.human_attribute_name(:author) %>:</strong>
  <%= @book.author %>
</p>

<p>
  <strong><%= Book.human_attribute_name(:picture) %>:</strong>
  <%= image_tag(@book.picture_url) if @book.picture.present? %>
</p>

<%= link_to t('button.edit'), edit_book_path(@book) %> |
<%= link_to t('button.back'), books_path %>